### ISSUE TITLE
Addin Indendation on Generated Code

### ISSUE THREAD

**Issue by Zaelarom** [cubewise-code/ti-helper#1]
Hello everyone,

We are trying to add indentation on generated code instead of space.
On Turbo Integrator Editor, we are using CTRL + i 
Do you know if it is possible to do that in TI Helper ? 

Thank you very much. 

T.

**Comment by lotsaram** [comment]
Hi @Zaelarom 
To do this you just use ^i (without {} brackets)  in the text file.

**Comment by Zaelarom** [comment]
Hi @lotsaram, it's work ! Thanks you
